version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest
    branches:
      only:
        - DEV
    steps:
      - run : ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no titbserverteam@107.167.190.53 "cd /app/testdeploy/ && bash ./deploy.sh"
